//! SeaORM Entity. Generated by sea-orm-codegen 0.5.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "object_relation")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i32,
    pub source_ref: String,
    pub target_ref: String,
    pub kind: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::object::Entity",
        from = "Column::TargetRef",
        to = "super::object::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Object2,
    #[sea_orm(
        belongs_to = "super::object::Entity",
        from = "Column::SourceRef",
        to = "super::object::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Object1,
}

impl ActiveModelBehavior for ActiveModel {}
