name: "build"

on:
  push:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/build-rust
        with:
          target: x86_64-unknown-linux-gnu
      - uses: ./.github/actions/build-rust
        with:
          target: x86_64-pc-windows-gnu
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            target/x86_64-pc-windows-gnu/release/threat-intel-fiesta.exe
            target/x86_64-unknown-linux-gnu/release/threat-intel-fiesta